const RAW_UPT_DATA = `DATA UPT
Aceh 
BAPAS KELAS I BANDA ACEH
BAPAS KELAS II KUTACANE
BAPAS KELAS II LHOK SEUMAWE
BAPAS KELAS II NAGAN RAYA
LAPAS KELAS IIA BANDA ACEH
LAPAS KELAS IIA LHOK SEUMAWE
LAPAS KELAS IIB BIREUEN
LAPAS KELAS IIB BLANGKEJEREN
LAPAS KELAS IIB BLANGPIDIE
LAPAS KELAS IIB IDI
LAPAS KELAS IIB KOTA BAKTI
LAPAS KELAS IIB KUALA SIMPANG
LAPAS KELAS IIB KUTACANE
LAPAS KELAS IIB LANGSA
LAPAS KELAS IIB LHOK SUKON
LAPAS KELAS IIB MEULABOH
LAPAS KELAS III CALANG
LAPAS KELAS III LHOK NGA
LAPAS KELAS III SINABANG
LAPAS NARKOTIKA KELAS IIB LANGSA
LAPAS PEREMPUAN KELAS IIB SIGLI
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II BANDA ACEH
RUTAN KELAS IIB BANDA ACEH
RUTAN KELAS IIB BENER MERIAH
RUTAN KELAS IIB JANTHO
RUTAN KELAS IIB SABANG
RUTAN KELAS IIB SIGLI
RUTAN KELAS IIB SINGKIL
RUTAN KELAS IIB TAKENGON
RUTAN KELAS IIB TAPAKTUAN

BALI
BAPAS KELAS I DENPASAR
BAPAS KELAS II KARANGASEM
LAPAS KELAS IIA KEROBOKAN
LAPAS KELAS IIA NARKOTIKA BANGLI
LAPAS KELAS IIB KARANGASEM
LAPAS KELAS IIB SINGARAJA
LAPAS KELAS IIB TABANAN
LAPAS PEREMPUAN KELAS IIA KEROBOKAN
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II KARANGASEM
RUTAN KELAS IIB BANGLI
RUTAN KELAS IIB GIANYAR
RUTAN KELAS IIB KLUNGKUNG
RUTAN KELAS IIB NEGARA
BANTEN
BAPAS KELAS I SERANG
BAPAS KELAS I TANGERANG
BAPAS KELAS II CIANGIR
LAPAS KELAS I TANGERANG
LAPAS KELAS IIA CILEGON
LAPAS KELAS IIA PEMUDA TANGERANG
LAPAS KELAS IIA PEREMPUAN TANGERANG
LAPAS KELAS IIA SERANG
LAPAS KELAS IIA TANGERANG
LAPAS KELAS III RANGKAS BITUNG
LAPAS TERBUKA KELAS IIB CIANGIR
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS I TANGERANG
RUTAN KELAS I TANGERANG
RUTAN KELAS IIB PANDEGLANG
RUTAN KELAS IIB SERANG
BENGKULU
BAPAS KELAS I BENGKULU
LAPAS KELAS IIA BENGKULU
LAPAS KELAS IIA CURUP
LAPAS KELAS IIB ARGAMAKMUR
LAPAS PEREMPUAN KELAS IIB BENGKULU
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II BENGKULU
RUTAN KELAS IIB BENGKULU
RUTAN KELAS IIB MANNA

D.I YOGYAKARTA
BAPAS KELAS I YOGYAKARTA
BAPAS KELAS II WONOSARI
LAPAS KELAS IIA NARKOTIKA YOGYAKARTA
LAPAS KELAS IIA YOGYAKARTA
LAPAS KELAS IIB SLEMAN
LAPAS KELAS IIB WONOSARI
LAPAS PEREMPUAN KELAS IIB YOGYAKARTA
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II YOGYAKARTA
RUTAN KELAS IIA YOGYAKARTA
RUTAN KELAS IIB BANTUL
RUTAN KELAS IIB WATES

DKI JAKARTA
BAPAS KELAS I JAKARTA BARAT
BAPAS KELAS I JAKARTA PUSAT
BAPAS KELAS I JAKARTA SELATAN
BAPAS KELAS I JAKARTA TIMUR UTARA
LAPAS KELAS I CIPINANG
LAPAS KELAS IIA SALEMBA
LAPAS NARKOTIKA KELAS II A JAKARTA
LAPAS PEREMPUAN KELAS IIA JAKARTA
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II JAKARTA
RUTAN KELAS I CIPINANG
RUTAN KELAS I JAKARTA PUSAT
RUTAN KELAS I PONDOK BAMBU

GORONTALO
BAPAS KELAS II GORONTALO
LAPAS KELAS IIA GORONTALO
LAPAS KELAS IIB BOALEMO
LAPAS KELAS IIB PAHUWATO
LAPAS PEREMPUAN KELAS III GORONTALO
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II GORONTALO

JAMBI
BAPAS KELAS I JAMBI
BAPAS KELAS II MUARA BUNGO
LAPAS KELAS IIA JAMBI
LAPAS KELAS IIB BANGKO
LAPAS KELAS IIB KUALA TUNGKAL
LAPAS KELAS IIB MUARA BULIAN
LAPAS KELAS IIB MUARA BUNGO
LAPAS KELAS IIB MUARA TEBO
LAPAS KELAS IIB SAROLANGUN
LAPAS NARKOTIKA KELAS IIB MUARA SABAK
LAPAS PEREMPUAN KELAS IIB JAMBI
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II MUARA BULIAN
RUTAN KELAS IIB SUNGAI PENUH

JAWA BARAT
BAPAS KELAS I BANDUNG
BAPAS KELAS I CIREBON
BAPAS KELAS II BEKASI
BAPAS KELAS II BOGOR
BAPAS KELAS II GARUT
BAPAS KELAS II SUBANG
LAPAS KELAS I CIREBON
LAPAS KELAS I SUKAMISKIN
LAPAS KELAS IIA BANCEUY BANDUNG
LAPAS KELAS IIA BEKASI
LAPAS KELAS IIA BOGOR
LAPAS KELAS IIA CIBINONG
LAPAS KELAS IIA CIKARANG
LAPAS KELAS IIA GARUT
LAPAS KELAS IIA KARAWANG
LAPAS KELAS IIA KUNINGAN
LAPAS KELAS IIA NARKOTIKA BANDUNG
LAPAS KELAS IIA NARKOTIKA CIREBON
LAPAS KELAS IIA PEREMPUAN BANDUNG
LAPAS KELAS IIA SUBANG
LAPAS KELAS IIA WARUNG KIARA
LAPAS KELAS IIB BANJAR
LAPAS KELAS IIB CIAMIS
LAPAS KELAS IIB CIANJUR
LAPAS KELAS IIB INDRAMAYU
LAPAS KELAS IIB MAJALENGKA
LAPAS KELAS IIB PURWAKARTA
LAPAS KELAS IIB SUKABUMI
LAPAS KELAS IIB SUMEDANG
LAPAS KELAS IIB TASIKMALAYA
LAPAS KHUSUS KELAS IIA GUNUNG SINDUR
LAPAS KHUSUS KELAS IIB SENTUL
LAPAS NARKOTIKA KELAS IIA GUNUNG SINDUR
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II BANDUNG
RUTAN KELAS I BANDUNG
RUTAN KELAS I CIREBON
RUTAN KELAS I DEPOK
RUTAN KELAS IIB GARUT
RUTAN PEREMPUAN KELAS II A BANDUNG

JAWA TENGAH
BAPAS KELAS I SEMARANG
BAPAS KELAS I SURAKARTA
BAPAS KELAS II KLATEN
BAPAS KELAS II MAGELANG
BAPAS KELAS II NUSAKAMBANGAN
BAPAS KELAS II PATI
BAPAS KELAS II PEKALONGAN
BAPAS KELAS II PURWOKERTO
LAPAS KELAS I BATU NUSAKAMBANGAN
LAPAS KELAS I SEMARANG
LAPAS KELAS IIA AMBARAWA
LAPAS KELAS IIA BESI NUSAKAMBANGAN
LAPAS KELAS IIA GLADAKAN NUSAKAMBANGAN
LAPAS KELAS IIA KEMBANG KUNING NUSAKAMBANGAN
LAPAS KELAS IIA KENDAL
LAPAS KELAS IIA MAGELANG
LAPAS KELAS IIA NARKOTIKA NUSAKAMBANGAN
LAPAS KELAS IIA NGASEMAN NUSAKAMBANGAN
LAPAS KELAS IIA PASIR PUTIH NUSAKAMBANGAN
LAPAS KELAS IIA PEKALONGAN
LAPAS KELAS IIA PEREMPUAN SEMARANG
LAPAS KELAS IIA PERMISAN NUSAKAMBANGAN
LAPAS KELAS IIA PURWOKERTO
LAPAS KELAS IIA SRAGEN
LAPAS KELAS IIB BATANG
LAPAS KELAS IIB BREBES
LAPAS KELAS IIB CILACAP
LAPAS KELAS IIB KLATEN
LAPAS KELAS IIB NIRBAYA NUSAKAMBANGAN
LAPAS KELAS IIB PATI
LAPAS KELAS IIB PEMUDA PLANTUNGAN
LAPAS KELAS IIB PURWODADI
LAPAS KELAS IIB SLAWI
LAPAS KELAS IIB TEGAL
LAPAS KELAS IIB TERBUKA KENDAL
LAPAS KELAS IIB TERBUKA NUSAKAMBANGAN
LAPAS KELAS IIB WONOGIRI
LAPAS KHUSUS KELAS IIA KARANGANYAR
LAPAS NARKOTIKA KELAS IIB PURWOKERTO
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS I KUTOARJO
RUTAN KELAS I SEMARANG
RUTAN KELAS I SURAKARTA
RUTAN KELAS IIA PEKALONGAN
RUTAN KELAS IIB BANJARNEGARA
RUTAN KELAS IIB BANYUMAS
RUTAN KELAS IIB BLORA
RUTAN KELAS IIB BOYOLALI
RUTAN KELAS IIB DEMAK
RUTAN KELAS IIB JEPARA
RUTAN KELAS IIB KEBUMEN
RUTAN KELAS IIB KUDUS
RUTAN KELAS IIB PEMALANG
RUTAN KELAS IIB PURBALINGGA
RUTAN KELAS IIB PURWOREJO
RUTAN KELAS IIB REMBANG
RUTAN KELAS IIB SALATIGA
RUTAN KELAS IIB TEMANGGUNG
RUTAN KELAS IIB WONOSOBO

JAWA TIMUR
BAPAS KELAS I MALANG
BAPAS KELAS I SURABAYA
BAPAS KELAS II BOJONEGORO
BAPAS KELAS II JEMBER
BAPAS KELAS II KEDIRI
BAPAS KELAS II MADIUN
BAPAS KELAS II PAMEKASAN
LAPAS KELAS I MADIUN
LAPAS KELAS I MALANG
LAPAS KELAS I SURABAYA
LAPAS KELAS IIA BANYUWANGI
LAPAS KELAS IIA BOJONEGORO
LAPAS KELAS IIA JEMBER
LAPAS KELAS IIA KEDIRI
LAPAS KELAS IIA NARKOTIKA PAMEKASAN
LAPAS KELAS IIA PAMEKASAN
LAPAS KELAS IIA PEREMPUAN MALANG
LAPAS KELAS IIA SIDOARJO
LAPAS KELAS IIB BLITAR
LAPAS KELAS IIB BONDOWOSO
LAPAS KELAS IIB JOMBANG
LAPAS KELAS IIB LAMONGAN
LAPAS KELAS IIB LUMAJANG
LAPAS KELAS IIB MOJOKERTO
LAPAS KELAS IIB NGAWI
LAPAS KELAS IIB PASURUAN
LAPAS KELAS IIB PROBOLINGGO
LAPAS KELAS IIB TUBAN
LAPAS KELAS IIB TULUNGAGUNG
LAPAS KELAS III ARJASA
LAPAS PEMUDA KELAS IIA MADIUN
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS I BLITAR
RUTAN KELAS I SURABAYA
RUTAN KELAS IIB BANGIL
RUTAN KELAS IIB BANGKALAN
RUTAN KELAS IIB GRESIK
RUTAN KELAS IIB KRAKSAAN
RUTAN KELAS IIB MAGETAN
RUTAN KELAS IIB NGANJUK
RUTAN KELAS IIB PACITAN
RUTAN KELAS IIB PONOROGO
RUTAN KELAS IIB SAMPANG
RUTAN KELAS IIB SITUBONDO
RUTAN KELAS IIB SUMENEP
RUTAN KELAS IIB TRENGGALEK
RUTAN PEREMPUAN KELAS IIA SURABAYA

KALIMANTAN BARAT
BAPAS KELAS I PONTIANAK
BAPAS KELAS II SAMBAS
BAPAS KELAS II SINTANG
LAPAS KELAS IIA PONTIANAK
LAPAS KELAS IIB KETAPANG
LAPAS KELAS IIB SINGKAWANG
LAPAS KELAS IIB SINTANG
LAPAS PEREMPUAN KELAS IIA PONTIANAK
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II SUNGAI RAYA
RUTAN KELAS IIA PONTIANAK
RUTAN KELAS IIB BENGKAYANG
RUTAN KELAS IIB LANDAK
RUTAN KELAS IIB MEMPAWAH
RUTAN KELAS IIB PUTUSSIBAU
RUTAN KELAS IIB SAMBAS
RUTAN KELAS IIB SANGGAU

KALIMANTAN SELATAN
BAPAS KELAS I BANJARMASIN
BAPAS KELAS II AMUNTAI
BAPAS KELAS II BATULICIN
LAPAS KELAS IIA BANJARMASIN
LAPAS KELAS IIA KOTABARU
LAPAS KELAS IIA NARKOTIKA KARANG INTAN
LAPAS KELAS IIB AMUNTAI
LAPAS KELAS IIB BANJARBARU
LAPAS KELAS IIB TANJUNG
LAPAS KELAS III BATULICIN
LAPAS PEREMPUAN KELAS IIA MARTAPURA
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS I MARTAPURA
RUTAN KELAS IIB BARABAI
RUTAN KELAS IIB KANDANGAN
RUTAN KELAS IIB MARABAHAN
RUTAN KELAS IIB PELAIHARI
RUTAN KELAS IIB RANTAU
RUTAN KELAS IIB TANJUNG

KALIMANTAN TENGAH
BAPAS KELAS I PALANGKARAYA
BAPAS KELAS II MUARA TEWEH
BAPAS KELAS II PANGKALAN BUN
BAPAS KELAS II SAMPIT
LAPAS KELAS IIA PALANGKARAYA
LAPAS KELAS IIB MUARA TEWEH
LAPAS KELAS IIB PANGKALAN BUN
PENGOLAH DATA LAPORAN PEMELIHARAAN PERLENGKAPAN
LAPAS KELAS III SUKAMARA
LAPAS NARKOTIKA KELAS IIA KASONGAN
LAPAS PEREMPUAN KELAS IIA PALANGKARAYA
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II PALANGKARAYA
RUTAN KELAS IIA PALANGKARAYA
RUTAN KELAS IIB BUNTOK
RUTAN KELAS IIB KUALA KAPUAS
RUTAN KELAS IIB TAMIANG LAYANG

KALIMANTAN TIMUR 
BAPAS KELAS I BALIKPAPAN
BAPAS KELAS I SAMARINDA
BAPAS KELAS II TARAKAN
LAPAS KELAS IIA BALIKPAPAN
LAPAS KELAS IIA BONTANG
LAPAS KELAS IIA SAMARINDA
LAPAS KELAS IIA TARAKAN
LAPAS KELAS IIA TENGGARONG
LAPAS KELAS IIB NUNUKAN
LAPAS NARKOTIKA KELAS IIA SAMARINDA
LAPAS PEREMPUAN KELAS IIA TENGGARONG
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II TENGGARONG
RUTAN KELAS I SAMARINDA
RUTAN KELAS IIA BALIKPAPAN
RUTAN KELAS IIB TANAH GROGOT
RUTAN KELAS IIB TANJUNG REDEP

KEPULAUAN BANGKA BELITUNG
BAPAS KELAS I PANGKAL PINANG 
BAPAS KELAS II TANJUNG PANDAN
LAPAS KELAS IIA PANGKAL PINANG
LAPAS KELAS IIB SUNGAI LIAT
LAPAS KELAS IIB TANJUNG PANDAN
LAPAS NARKOTIKA KELAS IIA PANGKAL PINANG
LAPAS PEREMPUAN KELAS III PANGKAL PINANG
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II PANGKAL PINANG
RUTAN KELAS IIB MUNTOK

KEPULAUAN RIAU
BAPAS KELAS I TANJUNG PINANG
BAPAS KELAS II BATAM
LAPAS KELAS IIA BATAM
LAPAS KELAS IIA NARKOTIKA TANJUNG PINANG
LAPAS KELAS IIA TANJUNG PINANG
LAPAS KELAS III DABO SINGKEP
LAPAS PEREMPUAN KELAS IIB BATAM
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II BATAM
RUTAN KELAS I TANJUNG PINANG
RUTAN KELAS IIA BATAM
RUTAN KELAS IIB TANJUNG BALAI KARIMUN

LAMPUNG 
BAPAS KELAS I BANDAR LAMPUNG
BAPAS KELAS II KOTABUMI
BAPAS KELAS II METRO
BAPAS KELAS II PRINGSEWU
LAPAS KELAS I BANDAR LAMPUNG
LAPAS KELAS IIA KALIANDA
LAPAS KELAS IIA KOTABUMI
LAPAS KELAS IIA METRO
LAPAS KELAS IIA NARKOTIKA BANDAR LAMPUNG
LAPAS KELAS IIA PEREMPUAN BANDAR LAMPUNG
LAPAS KELAS IIB GUNUNG SUGIH
LAPAS KELAS IIB KOTA AGUNG
LAPAS KELAS IIB WAYKANAN
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II BANDAR LAMPUNG
RUTAN KELAS I BANDAR LAMPUNG
RUTAN KELAS IIB KOTA AGUNG
RUTAN KELAS IIB KOTABUMI
RUTAN KELAS IIB KRUI
RUTAN KELAS IIB MENGGALA
RUTAN KELAS IIB SUKADANA

MALUKU
BAPAS KELAS II AMBON
BAPAS KELAS II SAUMLAKI
LAPAS KELAS IIA AMBON
LAPAS KELAS IIB PIRU
LAPAS KELAS IIB TUAL
LAPAS KELAS III BANDANAIRA
LAPAS KELAS III DOBO
LAPAS KELAS III GESER
LAPAS KELAS III NAMLEA
LAPAS KELAS III SAPARUA
LAPAS KELAS III SAUMLAKI
LAPAS KELAS III WAHAI
LAPAS KELAS III WONRELI
LAPAS PEREMPUAN KELAS III AMBON
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II AMBON
RUTAN KELAS IIA AMBON
RUTAN KELAS IIB MASOHI

MALUKU UTARA 
BAPAS KELAS II TERNATE
BAPAS KELAS II TIDORE
LAPAS KELAS IIA TERNATE
LAPAS KELAS IIB JAILOLO
LAPAS KELAS IIB SANANA
LAPAS KELAS IIB TOBELLO
LAPAS KELAS III LABUHA
LAPAS PEREMPUAN KELAS III TERNATE
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II TERNATE
RUTAN KELAS IIB SOA SIU
RUTAN KELAS IIB TERNATE
RUTAN KELAS IIB WEDA


NUSA TENGGARA BARAT
BAPAS KELAS I MATARAM
BAPAS KELAS II SUMBAWA BESAR
LAPAS KELAS IIA LOMBOK BARAT
LAPAS KELAS IIA SUMBAWA BESAR
LAPAS KELAS IIB DOMPU
LAPAS KELAS IIB SELONG
LAPAS PEREMPUAN KELAS III MATARAM
LAPAS TERBUKA KELAS IIB LOMBOK TENGAH
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II LOMBOK TENGAH
RUTAN KELAS IIB PRAYA
RUTAN KELAS IIB RABA BIMA

NUSA TENGGARA TIMUR 
BAPAS KELAS II KUPANG
BAPAS KELAS II WAIKABUBAK
LAPAS KELAS IIA KUPANG
LAPAS KELAS IIA WAINGAPU
LAPAS KELAS IIB ATAMBUA
LAPAS KELAS IIB ENDE
LAPAS KELAS IIB KALABAHI
LAPAS KELAS IIB TERBUKA WAIKABUBAK
LAPAS KELAS IIB WAIKABUBAK
LAPAS KELAS III BAA
LAPAS KELAS III LEMBATA
LAPAS PEREMPUAN KELAS IIB KUPANG
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS I KUPANG
RUTAN KELAS IIB BAJAWA
RUTAN KELAS IIB KEFAMENANU
RUTAN KELAS IIB KUPANG
RUTAN KELAS IIB LARANTUKA
RUTAN KELAS IIB MAUMERE
RUTAN KELAS IIB RUTENG
RUTAN KELAS IIB SOE

PAPUA 
BAPAS KELAS II JAYAPURA
BAPAS KELAS II KEEROM
BAPAS KELAS II MERAUKE
LAPAS KELAS IIA ABEPURA
LAPAS KELAS IIA NARKOTIKA JAYAPURA
LAPAS KELAS IIB BIAK
LAPAS KELAS IIB MERAUKE
LAPAS KELAS IIB NABIRE
LAPAS KELAS IIB SERUI
LAPAS KELAS IIB TIMIKA
LAPAS KELAS IIB WAMENA
LAPAS KELAS III TANAH MERAH
LAPAS PEREMPUAN KELAS III JAYAPURA
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II JAYAPURA

PAPUA BARAT
BAPAS KELAS I MANOKWARI
BAPAS KELAS II FAKFAK
BAPAS KELAS II SORONG
LAPAS KELAS IIB FAK-FAK
LAPAS KELAS IIB MANOKWARI
LAPAS KELAS IIB SORONG
LAPAS KELAS III KAIMANA
LAPAS KELAS III TEMINABUHAN
LAPAS PEREMPUAN KELAS III MANOKWARI
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II MANOKWARI
RUTAN KELAS IIB BINTUNI

RIAU
BAPAS KELAS I PEKANBARU
BAPAS KELAS II DUMAI
LAPAS KELAS IIA BAGAN SIAPI-API
LAPAS KELAS IIA BANGKINANG
LAPAS KELAS IIA BENGKALIS
LAPAS KELAS IIA PEKANBARU
LAPAS KELAS IIA TEMBILAHAN
LAPAS KELAS IIB PASIR PANGARAYAN
LAPAS KELAS IIB SELATPANJANG
LAPAS KELAS IIB TELUK KUANTAN
LAPAS KELAS III TERBUKA RUMBAI
LAPAS NARKOTIKA KELAS IIB RUMBAI
LAPAS PEREMPUAN KELAS IIA PEKANBARU
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II PEKANBARU
RUTAN KELAS I PEKANBARU
RUTAN KELAS IIB DUMAI
RUTAN KELAS IIB RENGAT
RUTAN KELAS IIB SIAK SRI INDRAPURA

SULAWESI BARAT 
BAPAS KELAS II POLEWALI
LAPAS KELAS IIB POLEWALI
LAPAS KELAS III MAMASA
LAPAS PEREMPUAN KELAS III MAMUJU
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II MAMUJU
RUTAN KELAS IIB MAJENE
RUTAN KELAS IIB MAMUJU
RUTAN KELAS IIB PASANG KAYU

SULAWESI SELATAN
BAPAS KELAS I MAKASSAR
BAPAS KELAS II PALOPO
BAPAS KELAS II WATAMPONE
LAPAS KELAS I MAKASSAR
LAPAS KELAS IIA BULUKUMBA
LAPAS KELAS IIA NARKOTIKA SUNGGUMINASA
LAPAS KELAS IIA PALOPO
LAPAS KELAS IIA PARE-PARE
LAPAS KELAS IIA PEREMPUAN SUNGGUMINASA
LAPAS KELAS IIA WATAMPONE
LAPAS KELAS IIB MAROS
LAPAS KELAS IIB TAKALAR
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II MAROS
RUTAN KELAS I MAKASSAR
RUTAN KELAS IIB BANTAENG
RUTAN KELAS IIB BARRU
RUTAN KELAS IIB ENREKANG
RUTAN KELAS IIB JENEPONTO
RUTAN KELAS IIB MAKALE
RUTAN KELAS IIB MALINO
RUTAN KELAS IIB MASAMBA
RUTAN KELAS IIB PANGKAJENE
RUTAN KELAS IIB PINRANG
RUTAN KELAS IIB SELAYAR
RUTAN KELAS IIB SENGKANG
RUTAN KELAS IIB SIDENRENG RAPANG
RUTAN KELAS IIB SINJAI
RUTAN KELAS IIB WATANSOPPENG

SULAWESI TENGAH 
BAPAS KELAS I PALU
BAPAS KELAS II LUWUK
LAPAS KELAS IIA PALU
LAPAS KELAS IIB AMPANA
LAPAS KELAS IIB LUWUK
LAPAS KELAS IIB TOLI-TOLI
LAPAS KELAS III KOLONEDALE
LAPAS KELAS III LEOK
LAPAS KELAS III PARIGI
LAPAS PEREMPUAN KELAS III PALU
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II PALU
RUTAN KELAS IIA PALU
RUTAN KELAS IIB DONGGALA
RUTAN KELAS IIB POSO

SULAWESI TENGGARA 
BAPAS KELAS II BAU-BAU
BAPAS KELAS II KENDARI
LAPAS KELAS IIA BAU-BAU
LAPAS KELAS IIA KENDARI
LAPAS PEREMPUAN KELAS III KENDARI
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II KENDARI
RUTAN KELAS IIA KENDARI
RUTAN KELAS IIB KOLAKA
RUTAN KELAS IIB RAHA
RUTAN KELAS IIB UNAAHA

SULAWESI UTARA 
BAPAS KELAS I MANADO
LAPAS KELAS IIA MANADO
LAPAS KELAS IIB BITUNG
LAPAS KELAS IIB TAHUNA
LAPAS KELAS IIB TONDANO
LAPAS KELAS IIB ULU SIAU
LAPAS KELAS III AMURANG
LAPAS KELAS III ENEMAWIRA
LAPAS KELAS III LIRUNG
LAPAS KELAS III TAGULANDANG
LAPAS KELAS III TAMAKO
LAPAS PEREMPUAN KELAS IIB MANADO
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II TOMOHON
RUTAN KELAS IIA MANADO

SUMATERA BARAT
BAPAS KELAS II BUKIT TINGGI
BAPAS KELAS I PADANG
LAPAS KELAS IIA BUKITTINGGI
LAPAS KELAS IIA PADANG
LAPAS KELAS IIB LUBUK BASUNG
LAPAS KELAS IIB MUARA SIJUNJUNG
LAPAS KELAS IIB PARIAMAN
LAPAS KELAS IIB SOLOK
LAPAS KELAS IIB TANJUNG PATI
LAPAS KELAS IIB TERBUKA PASAMAN
LAPAS KELAS III ALAHAN PANJANG
LAPAS KELAS III DHARMASRAYA
LAPAS KELAS III SULIKI
LAPAS KELAS III TALU
LAPAS NARKOTIKA KELAS III SAWAHLUNTO
LAPAS PEREMPUAN KELAS IIB PADANG
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS II PAYAKUMBUH
RUTAN KELAS IIB BATUSANGKAR
RUTAN KELAS IIB LUBUK SIKAPING
RUTAN KELAS IIB MANINJAU
RUTAN KELAS IIB MUARA LABUH
RUTAN KELAS IIB PADANG
RUTAN KELAS IIB PADANG PANJANG
RUTAN KELAS IIB PAINAN
RUTAN KELAS IIB SAWAHLUNTO


SUMATERA SELATAN
BAPAS KELAS II LAHAT
BAPAS KELAS II MUSI RAWAS UTARA
BAPAS KELAS II OKU INDUK
BAPAS KELAS II PALEMBANG
LAPAS KELAS I PALEMBANG
LAPAS KELAS IIA BANYUASIN
LAPAS KELAS IIA LAHAT
LAPAS KELAS IIA LUBUK LINGGAU
LAPAS KELAS IIA PEREMPUAN PALEMBANG
LAPAS KELAS IIA TANJUNG RAJA
LAPAS KELAS IIB EMPAT LAWANG
LAPAS KELAS IIB KAYU AGUNG
LAPAS KELAS IIB MARTAPURA
LAPAS KELAS IIB MUARA DUA
LAPAS KELAS IIB MUARA ENIM
LAPAS KELAS IIB SEKAYU
LAPAS KELAS III PAGAR ALAM
LAPAS KELAS III SAROLANGUN RAWAS
LAPAS NARKOTIKA KELAS IIA MUARA BELITI
LAPAS NARKOTIKA KELAS IIB BANYUASIN
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS I PALEMBANG
RUTAN KELAS I PALEMBANG
RUTAN KELAS IIB BATURAJA
RUTAN KELAS IIB PRABUMULIH



SUMATERA UTARA 
BAPAS KELAS I MEDAN
BAPAS KELAS II SIBOLGA
LAPAS KELAS I MEDAN
LAPAS KELAS IIA BINJAI
LAPAS KELAS IIA LABUHAN RUKU
LAPAS KELAS IIA NARKOTIKA PEMATANG SIANTAR
LAPAS KELAS IIA PANCUR BATU
LAPAS KELAS IIA PEMATANG SIANTAR
LAPAS KELAS IIA PEREMPUAN MEDAN
LAPAS KELAS IIA RANTAU PRAPAT
LAPAS KELAS IIA SIBOLGA
LAPAS KELAS IIB GUNUNG SITOLI
LAPAS KELAS IIB LUBUK PAKAM
LAPAS KELAS IIB PADANG SIDEMPUAN
LAPAS KELAS IIB PANYABUNGAN
LAPAS KELAS IIB SIBORONG-BORONG
LAPAS KELAS IIB TANJUNG BALAI ASAHAN
LAPAS KELAS IIB TEBING TINGGI DELI
LAPAS KELAS III BARUS
LAPAS KELAS III GUNUNG TUA
LAPAS KELAS III KOTA PINANG
LAPAS KELAS III KOTANOPAN
LAPAS KELAS III LABUAN BILIK
LAPAS KELAS III PANGURURAN
LAPAS KELAS III TELUK DALAM
LAPAS NARKOTIKA KELAS IIA LANGKAT
LAPAS PEMUDA KELAS III LANGKAT
LEMBAGA PEMBINAAN KHUSUS ANAK KELAS I MEDAN
RUTAN KELAS I LABUHAN DELI
RUTAN KELAS I MEDAN
RUTAN KELAS IIB BALIGE
RUTAN KELAS IIB HUMBANG HASUNDUTAN
RUTAN KELAS IIB KABANJAHE
RUTAN KELAS IIB NATAL
RUTAN KELAS IIB PANGKALAN BRANDAN
RUTAN KELAS IIB SIBUHUAN
RUTAN KELAS IIB SIDIKALANG
RUTAN KELAS IIB SIPIROK
RUTAN KELAS IIB TANJUNG PURA
RUTAN KELAS IIB TARUTUNG
RUTAN PEREMPUAN KELAS II A MEDAN`;

const PROVINCE_ALIASES = {
  ACEH: "Aceh",
  BALI: "Bali",
  BANTEN: "Banten",
  BENGKULU: "Bengkulu",
  "D.I YOGYAKARTA": "D.I Yogyakarta",
  "DKI JAKARTA": "DKI Jakarta",
  GORONTALO: "Gorontalo",
  JAMBI: "Jambi",
  "JAWA BARAT": "Jawa Barat",
  "JAWA TENGAH": "Jawa Tengah",
  "JAWA TIMUR": "Jawa Timur",
  "KALIMANTAN BARAT": "Kalimantan Barat",
  "KALIMANTAN SELATAN": "Kalimantan Selatan",
  "KALIMANTAN TENGAH": "Kalimantan Tengah",
  "KALIMANTAN TIMUR": "Kalimantan Timur",
  "KEPULAUAN BANGKA BELITUNG": "Kepulauan Bangka Belitung",
  "KEPULAUAN RIAU": "Kepulauan Riau",
  LAMPUNG: "Lampung",
  MALUKU: "Maluku",
  "MALUKU UTARA": "Maluku Utara",
  "NUSA TENGGARA BARAT": "Nusa Tenggara Barat",
  "NUSA TENGGARA TIMUR": "Nusa Tenggara Timur",
  PAPUA: "Papua",
  "PAPUA BARAT": "Papua Barat",
  RIAU: "Riau",
  "SULAWESI BARAT": "Sulawesi Barat",
  "SULAWESI SELATAN": "Sulawesi Selatan",
  "SULAWESI TENGAH": "Sulawesi Tengah",
  "SULAWESI TENGGARA": "Sulawesi Tenggara",
  "SULAWESI UTARA": "Sulawesi Utara",
  "SUMATERA BARAT": "Sumatera Barat",
  "SUMATERA SELATAN": "Sumatera Selatan",
  "SUMATERA UTARA": "Sumatera Utara",
};

const grouped = {};
let currentProvince = null;

RAW_UPT_DATA.split("\n").forEach((rawLine) => {
  const line = rawLine.trim();
  if (!line || line.toUpperCase() === "DATA UPT") return;

  const normalized = line.replace(/\s+/g, " ").toUpperCase();
  if (PROVINCE_ALIASES[normalized]) {
    currentProvince = PROVINCE_ALIASES[normalized];
    if (!grouped[currentProvince]) {
      grouped[currentProvince] = [];
    }
    return;
  }

  if (currentProvince) {
    grouped[currentProvince].push(line);
  }
});

export const UPT_BY_PROVINCE = grouped;
export const UPT_PROVINCES = Object.keys(grouped);
